### ISSUE TITLE
Consider adding verbose modes to commands

### ISSUE THREAD

**Issue by SimplicityGuy** [ssagar0/zoom#2]
For example, `zoom sync` should have at least 1 level of verbosity, but perhaps some more. With 1 level of verbosity (`-v`), I'd expect a summary of the sync, with 2 levels of verbosity (`-vv`) I'd expect a complete output of each sync.

**Comment by ssagar0** [comment]
That's a really good suggestion. I'll make sure to add it before zoom exits beta.

**Comment by ssagar0** [comment]
Fixed with 0.0.15.
